# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: right_arm
  joint_model_group_pose: RIGHT_ARM_INITIAL_POSE
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - bl_caster_rotation_joint
    - bl_caster_l_wheel_joint
    - bl_caster_r_wheel_joint
    - br_caster_rotation_joint
    - br_caster_l_wheel_joint
    - br_caster_r_wheel_joint
    - fl_caster_rotation_joint
    - fl_caster_l_wheel_joint
    - fl_caster_r_wheel_joint
    - fr_caster_rotation_joint
    - fr_caster_l_wheel_joint
    - fr_caster_r_wheel_joint
    - torso_lift_joint
    - head_pan_joint
    - head_tilt_joint
    - laser_tilt_mount_joint
    - left_shoulder_pan_joint
    - left_shoulder_lift_joint
    - left_upper_arm_roll_joint
    - left_elbow_flex_joint
    - left_forearm_roll_joint
    - left_wrist_flex_joint
    - left_wrist_roll_joint
    - left_left_gripper_finger_joint
    - left_right_gripper_finger_joint
    - right_shoulder_pan_joint
    - right_shoulder_lift_joint
    - right_upper_arm_roll_joint
    - right_elbow_flex_joint
    - right_forearm_roll_joint
    - right_wrist_flex_joint
    - right_wrist_roll_joint
    - right_left_gripper_finger_joint
    - right_right_gripper_finger_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: pr2/left_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - left_shoulder_pan_joint
      - left_shoulder_lift_joint
      - left_upper_arm_roll_joint
      - left_elbow_flex_joint
      - left_forearm_roll_joint
      - left_wrist_flex_joint
      - left_wrist_roll_joint
  - name: pr2/right_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - right_shoulder_pan_joint
      - right_shoulder_lift_joint
      - right_upper_arm_roll_joint
      - right_elbow_flex_joint
      - right_forearm_roll_joint
      - right_wrist_flex_joint
      - right_wrist_roll_joint
  - name: pr2/left_gripper_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
        - left_right_gripper_finger_joint
        - left_left_gripper_finger_joint
  - name: pr2/right_gripper_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
        - right_right_gripper_finger_joint
        - right_left_gripper_finger_joint