pr2:
    #list of controllers
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50

    torso_lift_joint_controller:
      type: position_controllers/JointTrajectoryController
      joints:
        - torso_lift_joint
      gains:
        torso_lift_joint: {p: 100, i: 0.1, d: 1.0}
      constraints:
        goal_time: 10.0                  # Override default

      state_publish_rate:  50            # Override default
      action_monitor_rate: 30            # Override default
      stop_trajectory_duration: 0        # Override default

    right_gripper_controller:
      type: "effort_controllers/JointTrajectoryController"
      joints:
        - right_right_gripper_finger_joint
        - right_left_gripper_finger_joint
      gains:
        right_right_gripper_finger_joint: {p: 100, i: 1, d: 10, i_clamp: 1.0}
        right_left_gripper_finger_joint: {p: 100, i: 1, d: 10, i_clamp: 1.0}
      constraints:
        goal_time: 3.0
        right_right_gripper_finger_joint:
          goal: 0.02
        right_left_gripper_finger_joint:
          goal: 0.02

    left_gripper_controller:
      type: "effort_controllers/JointTrajectoryController"
      joints:
        - left_right_gripper_finger_joint
        - left_left_gripper_finger_joint
      gains:
        left_right_gripper_finger_joint: {p: 100, i: 1, d: 10, i_clamp: 1.0}
        left_left_gripper_finger_joint: {p: 100, i: 1, d: 10, i_clamp: 1.0}
      constraints:
        goal_time: 3.0
        left_right_gripper_finger_joint:
          goal: 0.02
        left_left_gripper_finger_joint:
          goal: 0.02

    right_arm_controller:
      type: "position_controllers/JointTrajectoryController"
      joints:
        - right_shoulder_pan_joint
        - right_shoulder_lift_joint
        - right_upper_arm_roll_joint
        - right_elbow_flex_joint
        - right_forearm_roll_joint
        - right_wrist_flex_joint
        - right_wrist_roll_joint
      gains:
        right_shoulder_pan_joint: {p: 100, i: 0.01, d: 1}
        right_shoulder_lift_joint: {p: 100, i: 0.01, d: 1}
        right_upper_arm_roll_joint: {p: 100, i: 0.01, d: 1}
        right_elbow_flex_joint: {p: 100, i: 0.01, d: 1}
        right_forearm_roll_joint: {p: 100, i: 0.01, d: 1}
        right_wrist_flex_joint: {p: 100, i: 0.01, d: 1}
        right_wrist_roll_joint: {p: 100, i: 0.01, d: 1}

      constraints:
        goal_time: 10.0                  # Override default

      state_publish_rate:  50            # Override default
      action_monitor_rate: 30            # Override default
      stop_trajectory_duration: 0        # Override default

    left_arm_controller:
      type: "position_controllers/JointTrajectoryController"
      joints:
        - left_shoulder_pan_joint
        - left_shoulder_lift_joint
        - left_upper_arm_roll_joint
        - left_elbow_flex_joint
        - left_forearm_roll_joint
        - left_wrist_flex_joint
        - left_wrist_roll_joint
      gains:
        left_shoulder_pan_joint: {p: 100, i: 0.01, d: 1}
        left_shoulder_lift_joint: {p: 100, i: 0.01, d: 1}
        left_upper_arm_roll_joint: {p: 100, i: 0.01, d: 1}
        left_elbow_flex_joint: {p: 100, i: 0.01, d: 1}
        left_forearm_roll_joint: {p: 100, i: 0.01, d: 1}
        left_wrist_flex_joint: {p: 100, i: 0.01, d: 1}
        left_wrist_roll_joint: {p: 100, i: 0.01, d: 1}

      constraints:
        goal_time: 10.0                  # Override default

      state_publish_rate:  50            # Override default
      action_monitor_rate: 30            # Override default
      stop_trajectory_duration: 0        # Override default
      
    head_joint_controller:
      type: position_controllers/JointTrajectoryController
      joints:
        - head_pan_joint
        - head_tilt_joint
      gains:
        head_pan_joint: {p: 25.0, i: 12.0, d: 2.0}
        head_tilt_joint: {p: 49.6, i: 2.0, d: 1.6}
      constraints:
        goal_time: 10.0                  # Override default

      state_publish_rate:  50            # Override default
      action_monitor_rate: 30            # Override default
      stop_trajectory_duration: 0        # Override default
      
    laser_tilt_mount_joint_controller:
      type: position_controllers/JointTrajectoryController
      joints:
        - laser_tilt_mount_joint
      gains:
        laser_tilt_mount_joint: {p: 8.0, i: 0.1, d: 0.2}
      constraints:
        goal_time: 10.0                  # Override default

      state_publish_rate:  50            # Override default
      action_monitor_rate: 30            # Override default
      stop_trajectory_duration: 0        # Override default

    fl_caster_rotation_joint_controller:
      type: position_controllers/JointPositionController
      joint: fl_caster_rotation_joint
      pid: {p: 49.6, i: 2.0, d: 1.6}
    
    fr_caster_rotation_joint_controller:
      type: position_controllers/JointPositionController
      joint: fr_caster_rotation_joint
      pid: {p: 49.6, i: 2.0, d: 1.6}

    br_caster_rotation_joint_controller:
      type: position_controllers/JointPositionController
      joint: br_caster_rotation_joint
      pid: {p: 49.6, i: 2.0, d: 1.6}

    bl_caster_rotation_joint_controller:
      type: position_controllers/JointPositionController
      joint: bl_caster_rotation_joint
      pid: {p: 49.6, i: 2.0, d: 1.6}
    
    fr_caster_l_wheel_joint_controller:
      type: effort_controllers/JointVelocityController
      joint: fr_caster_l_wheel_joint
      pid: {p: 1000.0, i: 0.0, d: 100.0}
    fr_caster_r_wheel_joint_controller:
      type: effort_controllers/JointVelocityController
      joint: fr_caster_r_wheel_joint
      pid: {p: 1000.0, i: 0.0, d: 100.0}

    fl_caster_l_wheel_joint_controller:
      type: effort_controllers/JointVelocityController
      joint: fl_caster_l_wheel_joint
      pid: {p: 1000.0, i: 0.0, d: 100.0}
    fl_caster_r_wheel_joint_controller:
      type: effort_controllers/JointVelocityController
      joint: fl_caster_r_wheel_joint
      pid: {p: 1000.0, i: 0.0, d: 100.0}
    
    br_caster_l_wheel_joint_controller:
      type: effort_controllers/JointVelocityController
      joint: br_caster_l_wheel_joint
      pid: {p: 1000.0, i: 0.0, d: 100.0}
    br_caster_r_wheel_joint_controller:
      type: effort_controllers/JointVelocityController
      joint: br_caster_r_wheel_joint
      pid: {p: 1000.0, i: 0.0, d: 100.0}

    bl_caster_l_wheel_joint_controller:
      type: effort_controllers/JointVelocityController
      joint: bl_caster_l_wheel_joint
      pid: {p: 1000.0, i: 0.0, d: 100.0}
    bl_caster_r_wheel_joint_controller:
      type: effort_controllers/JointVelocityController
      joint: bl_caster_r_wheel_joint
      pid: {p: 1000.0, i: 0.0, d: 100.0}


