<?xml version="1.0" ?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:macro name="pr2_wheel_v0" params="suffix parent reflect">

        <joint name="${parent}_${suffix}_wheel_joint" type="continuous">
        <axis xyz="0 1 0" />
        <limit effort="7" velocity="15"/>
        <safety_controller  k_velocity="10" />
        <dynamics damping="1.0" friction="0.0" />
        <origin xyz="0 ${reflect*caster_wheel_offset_y} 0" rpy="0 0 0" />
        <parent link="${parent}_rotation_link"/>
        <child link="${parent}_${suffix}_wheel_link"/>
        </joint>
        <link name="${parent}_${suffix}_wheel_link">
        <inertial>
            <mass value="0.44036" />
            <origin xyz="0 0 0" />
            <inertia  ixx="0.012411765597" ixy="-0.000711733678" ixz="0.00050272983"
                    iyy="0.015218160428" iyz="-0.000004273467" izz="0.011763977943" />
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
            <mesh filename="package://pr2_tc_description/meshes/base_v0/wheel.dae" />
            </geometry>
            
            <material name="Wheel_${suffix}" />
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
            <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_length}" />
            </geometry>
        </collision>
        </link>

        <xacro:pr2_wheel_gazebo_v0 parent="${parent}" suffix="${suffix}" />
        <xacro:pr2_wheel_transmission_v0 parent="${parent}" suffix="${suffix}" reflect="${reflect}" />

    </xacro:macro>

    <xacro:macro name="pr2_wheel_transmission_v0" params="suffix parent reflect">        
        <transmission type="pr2_mechanism_model/SimpleTransmission" name="${parent}_${suffix}_wheel_trans">  
            <type>transmission_interface/SimpleTransmission</type>      
            <joint name="${parent}_${suffix}_wheel_joint">
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            </joint>
            <actuator name="${parent}_${suffix}_wheel_motor">
                <mechanicalReduction>${reflect * 624/35 * 80/18}</mechanicalReduction>
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            </actuator>
        </transmission>
    </xacro:macro>


    <xacro:macro name="pr2_caster_transmission_v0" params="suffix">
        <transmission type="pr2_mechanism_model/SimpleTransmission" name="${suffix}_rotation_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="${suffix}_rotation_joint">
                <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
            </joint>
            <actuator name="${suffix}_rotation_motor">            
                <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
                <mechanicalReduction>${-1 * 624/35 * 80/18}</mechanicalReduction>
            </actuator>
        </transmission>
    </xacro:macro>

    <xacro:macro name="pr2_wheel_gazebo_v0" params="suffix parent">
        <gazebo reference="${parent}_${suffix}_wheel_link">
        <mu1 value="100.0" />
        <mu2 value="100.0" />
        <kp  value="1000000.0" />
        <kd  value="1.0" />
        <maxVel  value="100.0" />
        <minDepth  value="0.0" />
        </gazebo>
    </xacro:macro>

    <xacro:macro name="pr2_caster_gazebo_v0" params="suffix">
        <gazebo reference="${suffix}_caster_rotation_link">
        <material value="Gazebo/Black" />
        </gazebo>
    </xacro:macro>

    <xacro:macro name="pr2_base_gazebo_v0" params="name">
        <gazebo reference="${name}_link">
            <selfCollide>false</selfCollide>
            <sensor type="contact" name="${name}_contact_sensor">
                <always_on>true</always_on>
                <update_rate>100.0</update_rate>
                <contact>
                <collision>${name}_link_collision</collision>
                </contact>
                <plugin name="${name}_gazebo_ros_bumper_controller" filename="libgazebo_ros_bumper.so">
                <alwaysOn>true</alwaysOn>
                <updateRate>100.0</updateRate>
                <bumperTopicName>${name}_bumper</bumperTopicName>
                <frameName>world</frameName>
                </plugin>
            </sensor>
        </gazebo>
        <gazebo reference="${name}_bellow_link">
            <material value="Gazebo/Black" />
        </gazebo>    
        <gazebo>
        <plugin name="p3d_base_controller" filename="libgazebo_ros_p3d.so">
            <alwaysOn>true</alwaysOn>
            <updateRate>100.0</updateRate>
            <bodyName>${name}_link</bodyName>
            <topicName>${name}_pose_ground_truth</topicName>
            <gaussianNoise>0.01</gaussianNoise>
            <frameName>map</frameName>
            <xyzOffsets>0 0 0</xyzOffsets>
            <rpyOffsets>0 0 0</rpyOffsets>
        </plugin>
        </gazebo>
    </xacro:macro>


    <xacro:macro name="pr2_caster_hub_v0" params="suffix parent *origin ref_position" >
        <joint name="${suffix}_rotation_joint" type="continuous">
        <axis xyz="0 0 1" />
        <limit effort="6.5" velocity="10"/> <!-- alpha tested velocity and effort limits -->
        <safety_controller  k_velocity="10" />
        <calibration rising="${ref_position}" />
        <dynamics damping="1.0" friction="0.0" />
        <xacro:insert_block name="origin" />
        <parent link="${parent}"/>
        <child link="${suffix}_rotation_link" />
        </joint>
        <link name="${suffix}_rotation_link">

        <inertial>
            <mass value="3.473082"/>
            <origin xyz="0 0 0.07" />
            <inertia  ixx="0.012411765597" ixy="-0.000711733678" ixz="0.00050272983"
                    iyy="0.015218160428" iyz="-0.000004273467" izz="0.011763977943" />
        </inertial>

        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
            <mesh filename="package://pr2_tc_description/meshes/base_v0/caster.stl" />
            </geometry>
            
            <material name="Caster" />
        </visual>

        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
            <mesh filename="package://pr2_tc_description/meshes/base_v0/caster_L.stl" />
            </geometry>
        </collision>
        </link>

        <!-- extensions -->
        <xacro:pr2_caster_transmission_v0 suffix="${suffix}" />
    </xacro:macro>

    <xacro:macro name="pr2_caster_v0" params="suffix parent *origin ref_position">

        <xacro:pr2_caster_hub_v0 parent="${parent}" suffix="${suffix}_caster"
                                ref_position="${ref_position}" >
        <xacro:insert_block name="origin" />
        </xacro:pr2_caster_hub_v0>

        <!-- wheel macros -->
        <xacro:pr2_wheel_v0 parent="${suffix}_caster" suffix="l" reflect="1" />
        <xacro:pr2_wheel_v0 parent="${suffix}_caster" suffix="r" reflect="-1" />

        <!-- extensions -->
        <xacro:pr2_caster_gazebo_v0 suffix="${suffix}" />
    </xacro:macro>



    <xacro:macro name="pr2_base" params="name">
            <link name="${name}_link">

            <inertial>
                <mass value="${base_mass}" />
                <origin xyz="${base_cg_x} ${base_cg_y} ${base_cg_z}" />
                <inertia ixx="5.652232699207" ixy="-0.009719934438" ixz="1.293988226423"
                        iyy="5.669473158652" iyz="-0.007379583694" izz="3.683196351726" />
            </inertial>

            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                <mesh filename="package://pr2_tc_description/meshes/base_v0/base.dae" />
                </geometry>
                
                <material name="White" />
            </visual>

            <collision>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                <mesh filename="package://pr2_tc_description/meshes/base_v0/base_L.stl" />
                </geometry>
            </collision>
            </link>

            <!-- base_footprint is a fictitious link(frame) that is on the ground right below base_link origin,
                navigation stack dedpends on this frame -->
            <link name="${name}_footprint">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                <box size="0.01 0.01 0.01" />
                </geometry>
                
                <material name="White" />
            </visual>
            <collision>
                <!-- represent base collision with a simple rectangular model, positioned by base_size_z s.t. top
                    surface of the collision box matches the top surface of the PR2 base -->
                <origin xyz="0 0 ${0.051+base_collision_size_z/2}" rpy="0 0 0" />
                <geometry>
                <box size="0.001 0.001 0.001" />
                </geometry>
            </collision>
            </link>

            <joint name="${name}_footprint_joint" type="fixed">
            <origin xyz="0 0 0.051" rpy="0 0 0" />
            <child link="${name}_link" />
            <parent link="${name}_footprint"/>
            </joint>

            <!-- visualize bellow -->
            <link name="${name}_bellow_link">
            <inertial>
                <mass value="1.0" />
                <origin xyz="0 0 0" />
                <inertia ixx="0.01" ixy="0.0" ixz="0.0"
                        iyy="0.01" iyz="0.0" izz="0.01" />
            </inertial>
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                <box size="0.05 0.37 0.3" />
                </geometry>
                <material name="Black" />
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                <box size="0.05 0.37 0.3" />
                </geometry>
            </collision>
            </link>
            <joint name="${name}_bellow_joint" type="fixed">
            <origin xyz="-0.29 0 0.8" rpy="0 0 0" />
            <parent link="${name}_link" />
            <child link="${name}_bellow_link"/>
            </joint>

            <!-- base laser -->
            <xacro:hokuyo_lx30_laser_v0 name="${name}_laser" parent="${name}" ros_topic="base_scan" update_rate="20" min_angle="-2.2689" max_angle="2.2689" >
            <origin xyz="${base_laser_x} ${base_laser_y} ${base_laser_z}" rpy="0 0 0" />
            </xacro:hokuyo_lx30_laser_v0>

            <!-- all four caster macros -->
            <xacro:pr2_caster_v0 suffix="fl" parent="${name}_link" ref_position="${cal_caster_fl - M_PI/4}" >
            <origin xyz="${caster_offset_x} ${caster_offset_y} ${caster_offset_z}" rpy="0 0 0" />
            </xacro:pr2_caster_v0>
            <xacro:pr2_caster_v0 suffix="fr" parent="${name}_link" ref_position="${cal_caster_fr - M_PI/4}" >
            <origin xyz="${caster_offset_x} ${-caster_offset_y} ${caster_offset_z}" rpy="0 0 0" />
            </xacro:pr2_caster_v0>
            <xacro:pr2_caster_v0 suffix="bl" parent="${name}_link" ref_position="${cal_caster_bl - M_PI / 4 + M_PI}" >
            <origin xyz="${-caster_offset_x} ${caster_offset_y} ${caster_offset_z}" rpy="0 0 0" />
            </xacro:pr2_caster_v0>
            <xacro:pr2_caster_v0 suffix="br" parent="${name}_link" ref_position="${cal_caster_br - M_PI / 4 + M_PI}"  >
            <origin xyz="${-caster_offset_x} ${-caster_offset_y} ${caster_offset_z}" rpy="0 0 0" />
            </xacro:pr2_caster_v0>

            <!-- gazebo extensions -->
            <xacro:pr2_base_gazebo_v0 name="${name}" />



    </xacro:macro>

 

</robot>